export type User = {
	aaa_org_id: string;
	aaa_user_id: string;
	api_key: string;
	domain_uuid: string;
	email: string;
	enable_webrtc: boolean;
	extension: string;
	extension_uuid: string;
	first_name: string;
	last_name: string;
	level: string;
	middle_name: string;
	role_group_name: string;
	role_groups: any;
	role_uuid: string;
	unit_name: string;
	unit_uuid: string;
	units: {
		account_number: string;
		address: string;
		bank_name: string;
		brand_name: string;
		city: string;
		country: string;
		created_at: number;
		created_by: string;
		date_of_incorporation: string;
		domain_uuid: string;
		email: string;
		level: string;
		note: string;
		parent_unit_uuid: string;
		phone_number: string;
		status: boolean;
		tax_code: string;
		unit_basis: boolean;
		unit_code: string;
		unit_config: {
			api_url: string;
			google_api_key: string;
			is_recording: boolean;
			logo: string;
			partner: string;
			payment_cost: string;
			version: string;
			zalo_api_key: string;
		};
		unit_leader: string;
		unit_name: string;
		unit_social: {
			facebook: string;
			gmail: string;
			google: string;
			instagram: string;
			linkedin: string;
			skype: string;
			telegram: string;
			tiktok: string;
			twitter: string;
			website: string;
			youtube: string;
			zalo: string;
		};
		unit_uuid: string;
		updated_at: number;
		updated_by: string;
	};
	user_enabled: string;
	user_status: string;
	user_uuid: string;
	username: string;
};

export type UserTableData = {
	id: string;
	unit_uuid: string;
	unit_name: string;
	username: string;
	first_name: string;
	last_name: string;
	email: string;
	level: string;
	role_group_name: string;
};

export type UserCreate = {
	email: string;
	enable_webrtc: boolean;
	extension: string;
	first_name: string;
	is_create_extension: boolean;
	is_remapping: boolean;
	last_name: string;
	level: string;
	middle_name: string;
	password?: string;
	role_uuid: string;
	unit_uuid: string;
	user_enabled: string;
	username: string;
};
